---
# tasks file for docker
- name: Install packages to allow apt to use a repository over HTTPS
  ansible.builtin.apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - bash-completion

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Set up the repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable"
    update_cache: true

- name: Install Docker Engine, Containerd, and Docker Compose
  ansible.builtin.apt:
    pkg:
    - "docker-ce=5:{{ docker_version }}~3-0~ubuntu-{{ ansible_facts['lsb']['codename'] }}"
    - "docker-ce-cli=5:{{ docker_version }}~3-0~ubuntu-{{ ansible_facts['lsb']['codename'] }}"
    - containerd.io 
    - docker-compose-plugin

- name: Add vagrant user to docker group
  ansible.builtin.user:
    name: vagrant
    group: docker

- name: Show IPs configured on virtual machine
  ansible.builtin.debug:
    msg: "{{ ansible_all_ipv4_addresses }}"