---
# tasks file for docker
- name: Install packages to allow apt to use a repository over HTTPS
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - bash-completion

- name: Add docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Set up repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable"
    update_cache: true

- name: Install docker Engine, containerd, and docker Compose (less than 23.0)
  ansible.builtin.apt:
    pkg:
      - "docker-ce=5:{{ docker_version }}~3-0~ubuntu-{{ ansible_facts['lsb']['codename'] }}"
      - "docker-ce-cli=5:{{ docker_version }}~3-0~ubuntu-{{ ansible_facts['lsb']['codename'] }}"
      - containerd.io
      - docker-compose-plugin
  when: docker_version < '23.0.0'

- name: Install docker Engine, containerd, and docker Compose (greater than or equal to 23.0)
  ansible.builtin.apt:
    pkg:
      - "docker-ce=5:{{ docker_version }}-1~ubuntu.{{ ansible_distribution_version }}~{{ ansible_facts['lsb']['codename'] }}"
      - "docker-ce-cli=5:{{ docker_version }}-1~ubuntu.{{ ansible_distribution_version }}~{{ ansible_facts['lsb']['codename'] }}"
      - containerd.io
      - docker-compose-plugin
  when: docker_version >= '23.0.0'

- name: Add vagrant user to docker group
  ansible.builtin.user:
    name: vagrant
    group: docker

- name: Remove repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable"
    update_cache: true
    state: absent

- name: Show ips configured on virtual machine
  ansible.builtin.debug:
    msg: "{{ ansible_all_ipv4_addresses }}"
